gem "rails", "~> 3.2.13"
gem 'sqlite3'
gem 'opal', git: "https://github.com/catprintlabs/opal.git"
#gem 'react-rails'
gem 'react-rails', path: "../../../react-rails"
gem 'opal-react', path: "../../../opal-react" #git: "https://github.com/catprintlabs/react.rb.git", :branch => 'opal-0.8'
gem 'opal-rails'
gem 'rspec-rails'
gem 'reactive_record', path: "../.."