source "http://rubygems.org"
gem "rails"
gem 'sqlite3'
#gem 'opal', "~> 0.8.0"
gem 'react-rails', "1.3.3"#, File.exist?("../../../react-rails") ? {path: "../../../react-rails"} :  {git: "https://github.com/catprintlabs/react-rails.git", :branch => 'isomorphic-methods-support'}
gem 'reactrb', path: "../../../reactive-ruby" #File.exist?("../../../reactive-ruby") ? {path: "../../../reactive-ruby"} :  {}
gem 'opal-rails', git: "https://github.com/reactrb/opal-rails.git"
#gem 'rspec-rails'
gem 'reactive-record', path: "../.."
gem 'jquery-cookie-rails'
gem 'byebug'
gem 'pry-rails'
gem 'pry-rescue'
gem 'opal-rspec-rails', git: 'https://github.com/reactrb/opal-rspec-rails.git'
