source "http://rubygems.org"
gem "rails" 
gem 'sqlite3'
gem 'opal', "~> 0.8"
gem 'react-rails', File.exist?("../../../react-rails") ? {path: "../../../react-rails"} :  {git: "https://github.com/catprintlabs/react-rails.git", :branch => 'isomorphic-methods-support'}
gem 'reactive-ruby', File.exist?("../../../reactive-ruby") ? {path: "../../../reactive-ruby"} :  {}
gem 'opal-rails'
gem 'rspec-rails'
gem 'reactive-record', path: "../.."
gem 'jquery-cookie-rails'
gem 'byebug'